### PR TITLE
Add golangci-lint for static check.

### LINKED ISSUE #48: Use golangci-lint for static check

### PR DESCRIPTION
**Pull request by zzheng2020**
Close #48 

Add golangci-lint for static check.

### CODE REVIEW

**Review by slhmy — CHANGES_REQUESTED** [review]
Hi! Thanks for contributing with this PR~

I should appologize to you that I didn't describe clear enough on #69.
It will be nice if you can adjust this PR with the following requirements:

1. Remove .golangci.yml (I will be more prefer to have the default settings, since I don't want to have too many customized options). You can give me reasons if you think keeping  it will be better.
2. Combine `Golangci Lint` & `Build and Test` action together into one job, this should save some resource (or `make build` will run twice since `test` and `cilint` are in different jobs)

**Comment by zzheng2020** [comment]
Hi, thanks for the review. :)
I have another question. Do you prefer to use golangci-lint to check existing code, or is it only applied to new pull requests?

**Comment by slhmy** [comment]
> Hi, thanks for the review. :) I have another question. Do you prefer to use golangci-lint to check existing code, or is it only applied to new pull requests?

If could, apply it to existing code, but we may push this target gently (or later). I not so sure if current code can totally pass the check.

I also decide to replace `go vet` to `golangcilint` in the `make check` target, but it's another task since this PR seems to aims on Github actions (and the toolkit works better than local binaries).

**Comment by zzheng2020** [comment]
Hi, the current code cannot pass the check.

set `skip-pkg-cache` and `skip-build-cache` to `true` due to these two issues. [issue 1](https://github.com/golangci/golangci-lint-action/issues/135), [issue 2](https://github.com/golangci/golangci-lint-action/issues/244).

**Review by slhmy — COMMENTED** [review]
LGTM, thanks!

**Review by slhmy — APPROVED** [review]

**Comment by slhmy** [comment]
You will receive invitations to join OJ Lab in your email, also there is a QQ group invitation o.O

**Pull request merged**
